os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt update
- sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script:
- bash build.sh

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: releases
  api_key:
    secure: mk0/aqvi4ky8RQ8h6vG+cw+wXHfLGyF8NmEigLuVtVbL5jz7zpvuO5i9HQkvsgNj7cXjUY2beepM17aF+LroLZUe21zpuhGib4k5rP9/Jxy8LBxIKMZZWg7HFqt5A29yAU4dYqPvV4Mig2nh0X1/HDcmnLLS8q1MFBPc655Sv//UERvlavvfXCL8rMjC+cX07eJoHpGJfyG+n6c6PiMKSnQ1sxjb1HADjP5HxdPHPl9BiKGkmKG2f92SKuR4FH5IfutcMWaCH+uSwzoE8RvqAEXspw0auLD1bLfbcatziR96DaK60DpSMUxrztImYnw+Yv/ratUHQjauk0qDOg+iPsem+OzoySutT3CLzENaeh54krKcZyc5rJFrhuF5mDbh2VnSZ1P/AszeYe/QUqCpbkzYIV8lWf7HMs+RfUec6qMpNTihIZjY5YyP6fff36N/jM50EZZNXdhifIpVdp3iOPeynktRvM2b/3elF6duerrPIUNlhmQHroQm3bU60Ksb+sceHHzuHIcKmPMTabg24Fvi36VCETn9rsyiilN2AIbjTGqR9TjOyg/Bp8QyCkvn1xNNtGqY2yI1AHn1LUMlkFwqsBc5jU+mJBOZYQcpmgQmJAt4Gnwi+1uOtR1tG+cF20YmRMhLqJQsKLQ/Jd0tyWlFhKmZHDc/jQ9VngZFXlI=
  file_glob: true
  file: "output/final/*.xz"
  draft: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|release$"
