os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt update
- sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script:
- bash build.sh

notifications:
  email:
    - false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
- bash build.sh -p

deploy:
  provider: releases
  api_key:
    secure: BGTSxW4omWylDIsfVL42ZtST03qnClRpIxsoBP+R1WSfm24EhEm9g2x+SaiX7/9+HvWvgSPRVYrms1Kn7mOOnGytz6v/o+CmyfFvpgPwqO1BCW4qWZY85ve5+7jrB367b1vlEtr8SmDFlgXSydLmyHtR4+Ah3AjdFB/2HgUCpM8qRWJumU3oBA0/BsuFRaUci6j7Tnv20rLg6Ti9k5fkbu+OuKpAszHTLVaPvlerZELI3MobOPPF6lNer/vPf/kmL3zsNY53nxz4mdy4bQY4aNa9Fg8A3Vy9lkWk9HMxOAk96/c8mYfAH9WSZRPp4IfxKmqhjuI01BCn3GVeQCAkt1+bISaxziC8PYU9wv7T6jm9ALnxOeYYSHBIDqnHmWNMxmU2gxCdL42iZ746l9tI0jPgTXVeaEQBNTNSCWeyuuitLWJOVMo//vvg0wWRSvxYU7SWQugKHklAq9WHfSsr7fRghETTfFWFSEDNMpA8INss7GMXXpSGoiDanF5h8GM/UmUk+YdKrNsxeY2TcycQoVg/f2D5LeIQ0PKVak+NGWw78MRHkriwG1FRrVC/v4VXRUluh27nn9JqvSqwpCasM72hTBJU64d2cAJY5fOSJwRwh1pdRA56fa5art3W3ySv9UKP9MXLfo/ZlCPYMU9JFB5Ad/3/mJjZq2a2K3tfoE8=
  file_glob: true
  file: "output/final/*.xz"
  draft: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master$|^release-.*$"
