os: linux
dist: bionic
sudo: required
language: go
go:
  - 1.16.x
install:
  - sudo apt update
  - sudo apt-get install gcc libgl1-mesa-dev xorg-dev
  - sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64
  - go get -u github.com/FiloSottile/vendorcheck
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.22.2
  - go mod vendor
script:
  - make test # Can be 'make check' once that is working.
  - make integration
  - make build-skybian-img 
  - make build-skybian-img BOARD=opi3 ARCH=arm64
  - make build-skybian-img BOARD=rpi ARCH=armhf
  - make build-skybian-img BOARD=rpi64 ARCH=arm64
  - make build-skyimager-gui
before_deploy:
  - bash build.sh -p
deploy:
  provider: releases
  file_glob: true
  file:
  - output/prime/final/*.tar.gz
  - output/opi3/final/*.tar.gz
  - output/rpi/final/*.tar.gz
  - output/rpi64/final/*.tar.gz
  - fyne-cross/bin/*.tar.gz
  draft: true
  prerelease: true
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
    tags: true
  api-key:
    secure: dufg623WCt05Ge96u2haQlP92Nd0Qsxkvv/uxe67oY/Q5Q7Rhig4yCEZ/DkK6nYPwaK7hl2vF3W1Cww2Fzq4sVHtBMZcDVvRhPZ2TTo43MlYuVvJg9Cct4g8zg8J8oLVvO2fGxRwLDG1zTjlW/k5y6dnTfcdOGKDfZ4NsPDy2GAHtlqpBRX/091Uj2h1jnsx8jYy15ezalBEEhuOUah+w/udloXjnR9HhcyQ+0WbqPX6LMpWqXG8wz/fGy1bH0ZhqyfHUBgP5oaGoN42LcZQ1TOWvPcrDqp31AWlZUMQDjW8qf2KYMs5+99Or9GkEX0BN4YdLqj2IRK4OSX02pEH8rtHK781TIlXwhAS+mH6tMhFZ4jsAfji3o3CuzQi5EBgvAP9l7VjoEF+EiLynzw63Ma0oAxmGolRAYdKMieAoeB/ii4K6PMOJfNfoPvqwZ6HZxEwsaZFjhk3DMAK1gTRZEHBfEC8VAFOF5m72oafotFbUGRxhdY71PsNbF+eb5oze9xw12cmUeRVfdIgFi0yWzpICXql/yVe34NutfmQz34xX5zFZlNiKiewm5EGjKRtP9DSEeiuFPWHWvPk3ypZ3ctEGUrzjoDTTPUwKZWpSn0zKV+yENitgrWf/BAsf2/ax7eCneaFUhfJd8H7mG7aDp7xF82yQOVK5CGfszETtd8=
